### ISSUE TITLE
add field SpatialForces

### ISSUE THREAD

**Issue by pFernbach** [loco-3d/multicontact-api#3]
ContactPhases should also store the spatialForces (6D) express at the effector frame.

**Comment by MedericFourmy** [comment]
`tsid.Contact6d.getForceGeneratorMatrix` stores a 6 by Nx3 matrix, N being the number of corners of each contact, that maps the corner forces vector returned by `getContactForce`. It would be more compact to add a list of these to the ContactSequence object rather thanthe whole 6d wrench trajectory.
