### ISSUE TITLE
Eigenpy 2.2.2

### ISSUE THREAD

**Issue by nim65s** [loco-3d/multicontact-api#5]
Hi,

Updating Eigenpy from 2.2.0 to 2.2.2 breaks many unit test here (in 16.04 & 18.04 / python 2 & 3), with eg.:

```
======================================================================
ERROR: test_contact_phase_contacts_variation (__main__.ContactPhaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "…/unittest/python/scenario.py", line 1166, in test_contact_phase_contacts_variation
    cp1 = buildRandomContactPhase()
  File "…/unittest/python/scenario.py", line 144, in buildRandomContactPhase
    addRandomCurvesValues(cp)
  File "…/unittest/python/scenario.py", line 90, in addRandomCurvesValues
    root = createRandomSE3Traj()
  File "…/unittest/python/scenario.py", line 48, in createRandomSE3Traj
    curve = SE3Curve(p0, p1, t_min, t_max)
ArgumentError: Python argument types in
    SE3Curve.__init__(SE3Curve, SE3, SE3, int, int)
did not match C++ signature:
    __init__(boost::python::api::object, curves::bezier_curve<double, double, true, Eigen::Matrix<double, 3, 1, 0, 3, 1> > {lvalue} translation_curve, Eigen::Matrix<double, 3, 3, 0, 3, 3> init_rotation, Eigen::Matrix<double, 3, 3, 0, 3, 3> end_rotation)
    __init__(boost::python::api::object, boost::shared_ptr<curves::curve_abc<double, double, true, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1> > > translation_curve,Eigen::Matrix<double, 3, 3, 0, 3, 3> init_rotation, Eigen::Matrix<double, 3, 3, 0, 3, 3> end_rotation)
    __init__(boost::python::api::object, boost::shared_ptr<curves::curve_abc<double, double, true, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1> > > translation_curve,boost::shared_ptr<curves::curve_abc<double, double, true, Eigen::Matrix<double, 3, 3, 0, 3, 3>, Eigen::Matrix<double, 3, 1, 0, 3, 1> > > rotation_curve)
    __init__(boost::python::api::object, Eigen::Matrix<double, -1, 1, 0, -1, 1> init_translation, Eigen::Matrix<double, -1, 1, 0, -1, 1> end_translation, Eigen::Matrix<double, 3, 3, 0, 3, 3> init_rotation, Eigen::Matrix<double, 3, 3, 0, 3, 3> end_rotation, double min, double max)
    __init__(boost::python::api::object, Eigen::Matrix<double, 4, 4, 0, 4, 4> init_transform, Eigen::Matrix<double, 4, 4, 0, 4, 4> end_transform, double min, double max)
    __init__(_object*)
```

(there are also issues where `SE3Curve.__init__(SE3Curve, SE3, SE3, float, float)` doesn't fit `__init__(boost::python::api::object, Eigen::Matrix<double, 4, 4, 0, 4, 4> init_transform, Eigen::Matrix<double, 4, 4, 0, 4, 4> end_transform, double min, double max)`,  in eg. `test_effector_trajectory_dict`)

Should this be reported to eigenpy as a regression there, or is it a known issue here ?

**Comment by nim65s** [comment]
Thanks for your help :)

I broke this `CURVES_WITH_PINOCCHIO_SUPORT` here: https://github.com/loco-3d/curves/commit/9939b99555c40a57773153e2810871b0515becbb#diff-af3b638bc2a3e6c650974192a53c7291R31

I'll fix that there.

And you're right, we can make this kind  of issues clearer with a check in CMakeLists. I'll take a look at it too :)

**Comment by pFernbach** [comment]
https://github.com/loco-3d/multicontact-api/commit/c458dd259f57d12d3dc90042ef866849c585ae90 and https://github.com/loco-3d/curves/pull/37 seems to fix the issue, can I close this issue ?

**Comment by nim65s** [comment]
yes, but c458dd2 is nowhere. I think merging https://gitlab.laas.fr/loco-3d/multicontact-api/-/merge_requests/12 & https://gitlab.laas.fr/loco-3d/multicontact-api/-/merge_requests/13 made a force push here, and unapplied #6 …

**Comment by nim65s** [comment]
re-applied in https://gepgitlab.laas.fr/loco-3d/multicontact-api/-/merge_requests/14
