### ISSUE TITLE
No package robotpkg-py3\*-multicontact-api & type mismatch when make install from source

### ISSUE THREAD

**Issue by youyou826** [loco-3d/multicontact-api#52]
Thank you for your project. I am currently attempting to download it, but I have encountered some difficulties and would greatly appreciate your assistance with the following issues:

1 .You mentioned that the project can be downloaded via the "robotpkg" , but even i check the whole website, I couldn't find the corresponding download package and was unable to successfully download it. http://robotpkg.openrobots.org/packages/debian/pub/dists/jammy/robotpkg/binary-amd64/
2. As an alternative, I tried downloading from the source code, but I encountered problems during the make install step.The main issue arises from an argument type mismatch in the call to the SE3Curve constructor.
![mul-api-bug](https://github.com/user-attachments/assets/959c93a2-6292-4e08-afef-ca813ab41ce1)

**Comment by nim65s** [comment]
This is broken: http://robotpkg.openrobots.org/rbulk/robotpkg-wip/wip/multicontact-api/
Thanks for the report, I'll try to fix this

**Comment by youyou826** [comment]
Thank you for your prompt response. look forward to the available one.

**Comment by nim65s** [comment]
This is fixed now
